### ISSUE TITLE
Ordnername für build-Skripte

### ISSUE THREAD

**Issue by christophervoigt** [chlorophyllkid/styleguide#1]
Im Moment haben wir eine Datei `/build.js`, welche JavaScript-Dateien kompiliert.
Als offene Punkte haben wir aber auch noch Tasks wie die Kompilierung von Sass oder Pug.
Diese offenen Tasks sollten ebenfalls als separate build-Dateien existieren, die über npm-scripts angesprochen werden können.

Meine Frage bezieht sich jetzt darauf, wie wir einen Ordner nennen, in denen diese Skripte einmal liegen?

Wir verwenden kein grunt oder gulp, weshalb diese Ordnernamen ausgeschlossen sind.
Mein Vorschlag wäre es den Ordner mit den build-Skripten `/build` zu nennen, wobei mir bewusst ist, dass dies auch die Bezeichnung eines _gebauten_ Ordners sein kann.

[Edit]: Ein weiterer Vorschlag, der mir bisher am besten gefällt, ist `/config`.

Vielleicht fällt euch ja auch noch etwas dazu ein.

**Comment by matthias85** [comment]
Die Begriffe bzw Ordner /compile, /bundle, /tasks, /build-tasks, /npm-tasks fallen mir dazu ein.

**Comment by christophervoigt** [comment]
`/tasks` find ich gut.

**Comment by Matthias-Hermsdorf** [comment]
/build-tasks und /npm-tasks finde ich gut.

Tasks an sich ist mir zu allgemein. Das kann auch eine Sammlung von Tickets sein.

**Comment by christophervoigt** [comment]
Ok, was haltet ihr noch von `/node_tasks` ?

Es passt vom _Wording_ her gut zum Ordner `/node_modules`, und enthält die Tasks die wir mit npm ausführen (bspw. `"build": "node build.js"`).
